package com.isep.kotlinproject.ui.auth

import android.app.Activity
import android.util.Log
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Email
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.android.gms.auth.api.signin.GoogleSignInOptions
import com.google.android.gms.common.api.ApiException
import com.isep.kotlinproject.R
import com.isep.kotlinproject.ui.components.AppPasswordInput
import com.isep.kotlinproject.ui.components.AppTextField
import com.isep.kotlinproject.viewmodel.AuthViewModel

@Composable
fun LoginScreen(
    viewModel: AuthViewModel,
    onNavigateToSignup: () -> Unit
) {
    var email by remember { mutableStateOf("") }
    var password by remember { mutableStateOf("") }

    val isLoading by viewModel.isLoading.collectAsState()
    val error by viewModel.error.collectAsState()
    val context = LocalContext.current
    
    // Google Sign-In configuration
    // Note: The web client ID is auto-generated by google-services plugin
    // It requires OAuth 2.0 client to be configured in Firebase Console
    val webClientId = try {
        context.getString(R.string.default_web_client_id)
    } catch (e: Exception) {
        // Fallback: Google Sign-In not configured
        null
    }
    
    val googleSignInClient = remember(webClientId) {
        webClientId?.let { clientId ->
            val gso = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
                .requestIdToken(clientId)
                .requestEmail()
                .build()
            GoogleSignIn.getClient(context, gso)
        }
    }
    
    // Google Sign-In launcher
    val googleSignInLauncher = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.StartActivityForResult()
    ) { result ->
        Log.d("LoginScreen", "Google Sign-In result: resultCode=${result.resultCode}")
        
        val task = GoogleSignIn.getSignedInAccountFromIntent(result.data)
        try {
            val account = task.getResult(ApiException::class.java)
            Log.d("LoginScreen", "Google account: ${account.email}, idToken present: ${account.idToken != null}")
            
            val idToken = account.idToken
            if (idToken != null) {
                Log.d("LoginScreen", "Calling signInWithGoogle with token")
                viewModel.signInWithGoogle(idToken)
            } else {
                Log.e("LoginScreen", "idToken is null - check SHA-1 fingerprint in Firebase Console")
                viewModel.setError("Google Sign-In failed: No ID token received. Check SHA-1 configuration.")
            }
        } catch (e: ApiException) {
            Log.e("LoginScreen", "Google sign-in failed with status code: ${e.statusCode}", e)
            val errorMessage = when (e.statusCode) {
                10 -> "Developer error: Check SHA-1 fingerprint and package name in Firebase Console"
                12501 -> "Sign-in cancelled by user"
                12502 -> "Sign-in currently in progress"
                7 -> "Network error"
                else -> "Google sign-in failed: ${e.statusCode}"
            }
            viewModel.setError(errorMessage)
        }
    }

    Box(
        modifier = Modifier
            .fillMaxSize()
            .background(MaterialTheme.colorScheme.background),
        contentAlignment = Alignment.Center
    ) {
        Card(
            modifier = Modifier
                .fillMaxWidth()
                .padding(24.dp),
            colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
            elevation = CardDefaults.cardElevation(defaultElevation = 8.dp)
        ) {
            Column(
                modifier = Modifier.padding(24.dp),
                horizontalAlignment = Alignment.CenterHorizontally
            ) {
                Text(
                    text = "Welcome Back", 
                    style = MaterialTheme.typography.headlineMedium,
                    fontWeight = FontWeight.Bold,
                    color = MaterialTheme.colorScheme.primary
                )
                
                Text(
                    text = "Sign in to continue", 
                    style = MaterialTheme.typography.bodyMedium,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )

                Spacer(modifier = Modifier.height(32.dp))

                AppTextField(
                    value = email,
                    onValueChange = { email = it },
                    label = "Email Address",
                    leadingIcon = Icons.Default.Email,
                    helpText = "Enter the email associated with your account."
                )

                Spacer(modifier = Modifier.height(16.dp))

                AppPasswordInput(
                    value = password,
                    onValueChange = { password = it },
                    label = "Password"
                )

                Spacer(modifier = Modifier.height(24.dp))

                if (isLoading) {
                    CircularProgressIndicator()
                } else {
                    Button(
                        onClick = { 
                            if (email.isNotBlank() && password.isNotBlank()) {
                                viewModel.login(email.trim(), password.trim()) 
                            }
                        },
                        modifier = Modifier.fillMaxWidth().height(50.dp),
                        enabled = email.isNotBlank() && password.isNotBlank()
                    ) {
                        Text("Log In")
                    }
                    
                    Spacer(modifier = Modifier.height(16.dp))
                    
                    // Divider with "or"
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        HorizontalDivider(modifier = Modifier.weight(1f))
                        Text(
                            text = "  or  ",
                            style = MaterialTheme.typography.bodySmall,
                            color = MaterialTheme.colorScheme.onSurfaceVariant
                        )
                        HorizontalDivider(modifier = Modifier.weight(1f))
                    }
                    
                    Spacer(modifier = Modifier.height(16.dp))
                    
                    // Google Sign-In Button - only show if configured
                    if (googleSignInClient != null) {
                        OutlinedButton(
                            onClick = {
                                googleSignInClient.signOut().addOnCompleteListener {
                                    val signInIntent = googleSignInClient.signInIntent
                                    googleSignInLauncher.launch(signInIntent)
                                }
                            },
                            modifier = Modifier.fillMaxWidth().height(50.dp),
                            border = BorderStroke(1.dp, MaterialTheme.colorScheme.outline)
                        ) {
                            Icon(
                                painter = painterResource(id = R.drawable.ic_google),
                                contentDescription = "Google",
                                tint = Color.Unspecified,
                                modifier = Modifier.size(24.dp)
                            )
                            Spacer(modifier = Modifier.width(12.dp))
                            Text(
                                text = "Continue with Google",
                                color = MaterialTheme.colorScheme.onSurface
                            )
                        }
                    }
                }

                if (error != null) {
                    Spacer(modifier = Modifier.height(16.dp))
                    Text(
                        text = error!!, 
                        color = MaterialTheme.colorScheme.error,
                        style = MaterialTheme.typography.bodySmall
                    )
                }

                Spacer(modifier = Modifier.height(16.dp))

                TextButton(onClick = onNavigateToSignup) {
                    Text("Don't have an account? Sign Up")
                }
            }
        }
    }
}
